Improve content for the "console dashboard "section
calimero-is-near/docs pull request #63
Opened 2023-05-26 01:21 UTC by fakela

- Refactor and enhance the content for the Console dashboard description in the Calimero Private Shard documentation. 

- This commit improves clarity, grammar, and structure of the information presented, providing a more comprehensive and user-friendly overview of the dashboard.

2023-05-30 13:10 UTC, emojapaula requested changes

2023-06-01 12:50 UTC, fakela commented on docs/getting_started/dashboard.md
> +    - **near-rpc**: This endpoint is used to interact with the Calimero GraphQL Indexer Service.
hmmm 🤔

2023-06-01 12:54 UTC, fakela commented on docs/getting_started/dashboard.md
> +    - **near-rpc**: This endpoint is used to interact with the Calimero GraphQL Indexer Service.
@emojapaula merge this and i'll create a seperate PR for this

2023-06-01 12:54 UTC, fakela commented on docs/getting_started/dashboard.md
> +    - **near-rpc**: This endpoint is used to interact with the Calimero GraphQL Indexer Service.
@emojapaula merge this and i'll create a seperate PR for this

2023-06-01 15:18 UTC, emojapaula approved these changes

2023-06-01 15:19 UTC, merged